# Locate gdal
# This module defines
# SIMULATIONCORE_EXT_DIR
# SIMULATIONCORE_FOUND, if false, do not try to link to gdal 
# SIMULATIONCORE_INCLUDE_DIR, where to find the headers
#
# $SIMULATIONCORE_DIR is an environment variable that would
# correspond to the ./configure --prefix=$DELTA3D
#
# Created by David Guthrie. 

SET(SIMULATIONCORE_DIR $ENV{SIMCORE_ROOT})
IF(SIMULATIONCORE_DIR)
  FILE(TO_CMAKE_PATH ${SIMULATIONCORE_DIR} SIMULATIONCORE_DIR)
ENDIF(SIMULATIONCORE_DIR)

FIND_PATH(SIMULATIONCORE_DIR include/SimCore/Export.h
    PATHS
      ${CMAKE_SOURCE_DIR}
      ${CMAKE_SOURCE_DIR}/../SimulationCore
    $ENV{SIMCORE_ROOT}
    /usr/local
    /usr
    /sw # Fink
    /opt/local # DarwinPorts
    /opt/csw # Blastwave
    /opt
)

FIND_PATH(SIMULATIONCORE_INCLUDE_DIR NAMES SimCore/Export.h PATH_SUFFIXES include inc
    PATHS
    ${SIMULATIONCORE_DIR}
    NO_DEFAULT_PATH
)

FIND_FILE(SIMULATIONCORE_LIB_DIR NAMES lib
    PATHS
    ${SIMULATIONCORE_DIR}
    NO_DEFAULT_PATH
)

IF (WIN32)
   SET(EXT_INCLUDE_DIR_NAME win32)
ELSE (WIN32) 
   IF (APPLE)
      SET(EXT_INCLUDE_DIR_NAME darwin)
   ELSE (APPLE)
      SET(EXT_INCLUDE_DIR_NAME linux2)      
   ENDIF (APPLE)
ENDIF (WIN32)

FIND_FILE( SIMULATIONCORE_EXT_DIR NAMES ${EXT_INCLUDE_DIR_NAME}
    PATHS
    ${SIMULATIONCORE_DIR}/ext/include
    NO_DEFAULT_PATH
)

SET(SIMCORE_LIBRARY SimCore)
SET(SIMCOREHLA_LIBRARY SimCoreHLA)
SET(STEALTHGM_LIBRARY StealthGMApp)
SET(STEALTHQT_LIBRARY StealthQtLib)
SET(OSGEPHEMERIS_LIBRARY osgEphemeris)

IF (WIN32)
SET(SIMCORE_LIBRARY_DEBUG SimCored)
SET(SIMCOREHLA_LIBRARY_DEBUG SimCoreHLAd)
SET(STEALTHGM_LIBRARY_DEBUG StealthGMAppd)
SET(STEALTHQT_LIBRARY_DEBUG StealthQtLibd)
SET(OSGEPHEMERIS_LIBRARY_DEBUG osgEphemerisd)
ENDIF (WIN32)

SET(SIMULATIONCORE_FOUND "NO")
IF(SIMCORE_LIBRARY AND SIMULATIONCORE_INCLUDE_DIR AND SIMULATIONCORE_LIB_DIR)
    SET(SIMULATIONCORE_FOUND "YES")
ENDIF(SIMCORE_LIBRARY AND SIMULATIONCORE_INCLUDE_DIR AND SIMULATIONCORE_LIB_DIR)
