# Locate dtPhysX
# This module defines
# DTPHYSX_EXT_DIR
# DTPHYSX_FOUND, if false, do not try to link to gdal 
# DTPHYSX_INCLUDE_DIR, where to find the headers
#
# $DTPHYSX_DIR is an environment variable that would
# correspond to the ./configure --prefix=$DTPHYSX
#
# Created by David Guthrie. 

SET(DTPHYSX_DIR_SEARCH $ENV{DTPHYSX_ROOT})
IF(DTPHYSX_DIR_SEARCH)
  FILE(TO_CMAKE_PATH ${DTPHYSX_DIR_SEARCH} DTPHYSX_DIR_SEARCH)
  SET(DTPHYSX_DIR_SEARCH ${DTPHYSX_DIR_SEARCH}/include)
ENDIF(DTPHYSX_DIR_SEARCH)

SET(DTPHYSX_DIR_SEARCH
  ${DTPHYSX_DIR_SEARCH}
  ${CMAKE_SOURCE_DIR}/../dtPhysX
  ${CMAKE_SOURCE_DIR}/../dtAgeia
  ${CMAKE_SOURCE_DIR}/../dtAgeiaPhysX
)


FIND_PATH(DTPHYSX_INCLUDE_DIR NxAgeiaWorldComponent.h PATH_SUFFIXES include inc
    PATHS
    ${DTPHYSX_DIR_SEARCH}
)

MACRO(FIND_DT_LIBRARY MYLIBRARY MYLIBRARYNAMES)

    FIND_LIBRARY(${MYLIBRARY}
        NAMES ${MYLIBRARYNAMES} PATH_SUFFIXES lib
        PATHS
        ${DTPHYSX_DIR_SEARCH}
    )

ENDMACRO(FIND_DT_LIBRARY LIBRARY LIBRARYNAMES)

FIND_DT_LIBRARY(DTPHYSX_LIBRARY dtPhysX)

IF (WIN32)
   FIND_DT_LIBRARY(DTPHYSX_LIBRARY dtPhysXd)
ENDIF (WIN32)

SET(DTPHYSX_FOUND "NO")
IF(DTPHYSX_LIBRARY AND DTPHYSX_INCLUDE_DIR)
    SET(DTPHYSX_FOUND "YES")
ENDIF(DTPHYSX_LIBRARY AND DTPHYSX_INCLUDE_DIR)
