/* -*-c++-*-
* Simulation Core
* Copyright 2007-2008, Alion Science and Technology
*
* This library is free software; you can redistribute it and/or modify it under
* the terms of the GNU Lesser General Public License as published by the Free
* Software Foundation; either version 2.1 of the License, or (at your option)
* any later version.
*
* This library is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
* FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
* details.
*
* You should have received a copy of the GNU Lesser General Public License
* along with this library; if not, write to the Free Software Foundation, Inc.,
* 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
*
* This software was developed by Alion Science and Technology Corporation under
* circumstances in which the U. S. Government may have rights in the software.
* @author Curtiss Murphy
*/
#ifndef DELTA_SIMCOREVERSION
#define DELTA_SIMCOREVERSION

/**
 * The data in this file is generated by using the SubWCVer tool from Tortoise SVN in Windows. 
 * This tool takes a source file, SimCoreVersionTemplate.h and looks for predefined symbols. 
 * These symbols are then replaced by pulling out the current SVN version numbers and generating
 * the live file, SimCoreVersion.h. The manual step requires you to run SubWCVer when you want the 
 * versions to update, but will not require you to update code otherwise. 
 *
 * To run the tool, use the following command (manual or as a build step) from this directory:
 *     "c:\Program Files\TortoiseSVN\bin\SubWCRev.exe" ..\.. SimCoreVersionTemplate.h SimCoreVersion.h
 * 
 */


namespace SimCore
{
   std::string SIMCORE_SVN_REVISION("3174");
   std::string SIMCORE_SVN_DATE("2011/04/05 15:49:49");
   std::string SIMCORE_BUILD_DATE("2011/04/05 17:05:41");
}

#endif
