# Locate gdal
# This module defines
# DTCORE_LIBRARY
# DELTA3D_EXT_DIR
# DELTA3D_FOUND, if false, do not try to link to gdal 
# DELTA3D_INCLUDE_DIR, where to find the headers
#
# $DELTA3D_DIR is an environment variable that would
# correspond to the ./configure --prefix=$DELTA3D
#
# Created by David Guthrie. 

FIND_PATH(DELTA_DIR inc/dtCore/dt.h
    PATHS
    ${CMAKE_SOURCE_DIR}/../delta3d
    $ENV{DELTA_ROOT}
    $ENV{DELTA_INC}
    ~/Library/Frameworks
    /Library/Frameworks
    /usr/local
    /usr
    /sw # Fink
    /opt/local # DarwinPorts
    /opt/csw # Blastwave
    /opt
    [HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControl\\Control\\Session\ Manager\\Environment;DELTA_ROOT]
    /usr/freeware/include
)

FIND_PATH(DELTA3D_INCLUDE_DIR dtCore/dt.h
    ${DELTA_DIR}/inc
)

FIND_PATH( DELTA3D_EXT_DIR inc
    ${DELTA_DIR}/ext
)

MACRO(FIND_DT_LIBRARY MYLIBRARY MYLIBRARYNAMES)

    FIND_LIBRARY(${MYLIBRARY}
        NAMES ${MYLIBRARYNAMES}
        PATHS
        ${DELTA_DIR}/lib
        $ENV{DELTA_LIB}
        ~/Library/Frameworks
        /Library/Frameworks
        /usr/local/lib
        /usr/lib
        /sw/lib
        /opt/local/lib
        /opt/csw/lib
        /opt/lib
        [HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControl\\Control\\Session\ Manager\\Environment;DELTA_ROOT]/lib
        /usr/freeware/lib64
    )

ENDMACRO(FIND_DT_LIBRARY LIBRARY LIBRARYNAMES)

FIND_DT_LIBRARY(DTUTIL_LIBRARY dtUtil)
FIND_DT_LIBRARY(DTCORE_LIBRARY dtCore)
FIND_DT_LIBRARY(DTABC_LIBRARY dtABC)
FIND_DT_LIBRARY(DTDAL_LIBRARY dtDAL)
FIND_DT_LIBRARY(DTAI_LIBRARY dtAI)
FIND_DT_LIBRARY(DTGAME_LIBRARY dtGame)
FIND_DT_LIBRARY(DTAUDIO_LIBRARY dtAudio)
FIND_DT_LIBRARY(DTANIM_LIBRARY dtAnim)
FIND_DT_LIBRARY(DTGUI_LIBRARY dtGUI)
FIND_DT_LIBRARY(DTINSPECTOR_LIBRARY dtInspector)
FIND_DT_LIBRARY(DTSCRIPT_LIBRARY dtScript)
FIND_DT_LIBRARY(DTTERRAIN_LIBRARY dtTerrain)
FIND_DT_LIBRARY(DTNET_LIBRARY dtNet)
FIND_DT_LIBRARY(DTNETGM_LIBRARY dtNetGM)
FIND_DT_LIBRARY(DTHLAGM_LIBRARY dtHLAGM)
FIND_DT_LIBRARY(DTDIS_LIBRARY dtDIS)
FIND_DT_LIBRARY(DTINPUT_PLIB_LIBRARY dtInputPLIB)
FIND_DT_LIBRARY(DTACTORS_LIBRARY dtActors)
FIND_DT_LIBRARY(DTANIM_LIBRARY dtAnim)
FIND_DT_LIBRARY(DTLMS_LIBRARY dtLMS)
FIND_DT_LIBRARY(TEST_ACTOR_LIBRARY testActorLibrary)
FIND_DT_LIBRARY(TEST_GAME_ACTOR_LIBRARY testGameActorLibrary)

IF (WIN32)
FIND_DT_LIBRARY(DTUTIL_LIBRARY_DEBUG dtUtild)
FIND_DT_LIBRARY(DTCORE_LIBRARY_DEBUG dtCored)
FIND_DT_LIBRARY(DTABC_LIBRARY_DEBUG dtABCd)
FIND_DT_LIBRARY(DTDAL_LIBRARY_DEBUG dtDALd)
FIND_DT_LIBRARY(DTAI_LIBRARY_DEBUG dtAId)
FIND_DT_LIBRARY(DTGAME_LIBRARY_DEBUG dtGamed)
FIND_DT_LIBRARY(DTAUDIO_LIBRARY_DEBUG dtAudiod)
FIND_DT_LIBRARY(DTANIM_LIBRARY_DEBUG dtAnimd)
FIND_DT_LIBRARY(DTGUI_LIBRARY_DEBUG dtGUId)
FIND_DT_LIBRARY(DTINSPECTOR_LIBRARY_DEBUG dtInspectord)
FIND_DT_LIBRARY(DTSCRIPT_LIBRARY_DEBUG dtScriptd)
FIND_DT_LIBRARY(DTTERRAIN_LIBRARY_DEBUG dtTerraind)
FIND_DT_LIBRARY(DTNET_LIBRARY_LIBRARY dtNetd)
FIND_DT_LIBRARY(DTNETGM_LIBRARY_DEBUG dtNetGMd)
FIND_DT_LIBRARY(DTHLAGM_LIBRARY dtHLAGMd)
FIND_DT_LIBRARY(DTDIS_LIBRARY dtDISd)
FIND_DT_LIBRARY(DTINPUT_PLIB_LIBRARY_DEBUG dtInputPLIBd)
FIND_DT_LIBRARY(DTACTORS_LIBRARY_DEBUG dtActorsd)
FIND_DT_LIBRARY(DTANIM_LIBRARY_DEBUG dtAnimd)
FIND_DT_LIBRARY(DTLMS_LIBRARY_DEBUG dtLMSd)
FIND_DT_LIBRARY(TEST_ACTOR_LIBRARY_DEBUG testActorLibraryd)
FIND_DT_LIBRARY(TEST_GAME_ACTOR_LIBRARY_DEBUG testGameActorLibraryd)
ENDIF (WIN32)

SET(DELTA3D_FOUND "NO")
IF(DTCORE_LIBRARY AND DELTA3D_INCLUDE_DIR)
    SET(DELTA3D_FOUND "YES")
ENDIF(DTCORE_LIBRARY AND DELTA3D_INCLUDE_DIR)
