# Build script for the src directory
import os

Import('*')

#modules = []

#for module in modules :
#	SConscript(dirs = [module], build_dir = os.path.join( module, 'linux-g++-'+mode ), duplicate = 0)

srcs = [env.SGlob('SimCore/*.cpp')] + [env.SGlob('SimCore/Actors/*.cpp')] + [env.SGlob('SimCore/Tools/*.cpp')] + [env.SGlob('SimCore/Components/*.cpp')]
deps = [ 'osgGA', 'osgProducer', 'Producer', 'OpenThreads', 'xerces-c', 'cal3d', 'osgDB', 'osgParticle', 
        'osgText', 'osgFX', 'osgSim', 'osg', 'osgUtil', 'rbody', 'gdal', 'dtGui',
        'dtAudio', 'dtCore', 'dtAnim', 'dtChar', 'dtUtil', 'dtDAL', 'dtGame', 'dtAI', 'dtActors', 
        'dtABC', 'dtHLAGM', 'dtGUI', 'CEGUIBase', 'CEGUIOpenGLRenderer', 'opengl', 'osgEphemeris' ] + env['rtiLibs']

defines = []
if env.get('ageia') != 0 :
   deps += ['dtAgeiaPhysX', 'NxCooking', 'NxCharacter', 'NxExtensions', 'PhysXLoader']
   defines += ['AGEIA_PHYSICS']

if env['OS'] == 'windows':
   defines += ['DVTE_LIBRARY', 'NOMINMAX']

env.BuildLib('SimViewerCore', srcs, deps, defines, prefixHeader='include/prefix/SimCorePrefix.h')

SConscript(dirs = ["StealthViewer"], duplicate = 0)
