TOPDIR = ../
include $(DWMAKE)/makedefs

DIRS = \
    MakeMoonImages\
    MakeSunImage\
    osgEphemerisLib\
    osgEphemerisPlugin\
    Gui\
    CallbackExample\
    Viewer\


include $(DWMAKE)/makedirrules
